/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Campo;
import Clases.EstadoProyecto;
import Clases.Laboreo;
import Clases.Lotes;
import Clases.Proyecto;
import Controladora.Controlador;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezest
 */
public class ProyectosVigentes extends javax.swing.JFrame {
Controlador control = new Controlador();
DefaultTableModel dtmPro = new DefaultTableModel();
DefaultTableModel dtmLpro = new DefaultTableModel();
DefaultTableModel dtmPRE = new DefaultTableModel();
DefaultTableModel dtmPOST = new DefaultTableModel();



List <Integer> indices = new ArrayList();

List <Proyecto> proyectos = new ArrayList();
List <Lotes> lotesP=  new ArrayList();
List <Campo> CampoP=  new ArrayList();
List <Laboreo> laboreopre=  new ArrayList();
List <Laboreo> laboreopost=  new ArrayList();  




    public ProyectosVigentes(Controlador control2) {
        initComponents();
        control = control2;
        String [] titulo = new String [] {"Id Proyecto","Descripcion"};
        String [] titulo2 = new String [] {"Id Campo","Nombre","Id Lote ","Proyecto","Estado del Proyecto","Laboreo Actual"};
        String [] titulopre = new String [] {"Preparacion"};
        String [] titulopost = new String [] {"Post Siembra"};
        dtmPro.setColumnIdentifiers(titulo);
        dtmLpro.setColumnIdentifiers(titulo2);
        dtmPRE.setColumnIdentifiers(titulopre);
        dtmPOST.setColumnIdentifiers(titulopost);
        
        tablaProyectos.setModel(dtmPro);
        tablaLotesP.setModel(dtmLpro);
        tablaPRE.setModel(dtmPRE);
        tablaPOST.setModel(dtmPOST);
        
        
        proyectos=control.obtenerProyectos();
        
                proyectos.stream().map((obj) -> new String []{Long.toString(obj.getIdProyecto()),obj.getDescripcion()}).forEachOrdered((proy) -> {
        dtmPro.addRow(proy);
        });  
                

            
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPOST = new javax.swing.JTable();
        Finalizar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Reiniciar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLotesP = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaPRE = new javax.swing.JTable();
        Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaPOST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPOST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPOSTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPOST);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 100));

        Finalizar.setText("Finalizar");
        jPanel1.add(Finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 90, -1));

        Cancelar.setText("Cancelar");
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 90, -1));

        jLabel1.setText("Proyectos Vigentes:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        Reiniciar.setText("Reiniciar");
        jPanel1.add(Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 90, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProyectosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProyectos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 580, 100));

        tablaLotesP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaLotesP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLotesPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaLotesP);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 580, 100));

        tablaPRE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPREMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaPRE);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 100));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        Inicio ini = new Inicio(control);
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_volverActionPerformed

    private void tablaProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProyectosMouseClicked
        int indice;
        lotesP.clear();
        Proyecto p = new Proyecto();
        dtmLpro.setRowCount(0);
        dtmPRE.setRowCount(0);
        dtmPOST.setRowCount(0);
        Campo c = new Campo();
        indice=tablaProyectos.getSelectedRow();
        
        p=proyectos.get(indice);
        lotesP=p.getLotes();
        laboreopre=p.getLaboreosPre();
        laboreopost=p.getLaboreosPost();
        for (Laboreo l :laboreopre){
            
            String [] rowLAB = new String[] {String.valueOf(l.getIdLaboreo())+ " - " + l.getDescripcion()};
            dtmPRE.addRow(rowLAB);
        
        }
        
        for (Laboreo l :laboreopost){
            
            String [] rowLAB = new String[] {String.valueOf(l.getIdLaboreo())+ " - " + l.getDescripcion()};
            dtmPOST.addRow(rowLAB);
        
        }
        
        
        
        
        
        
        for (Lotes l :p.getLotes()){
            c=control.buscarCampo(l.getFk_Campo());
            String [] rowLotes = new String[] {String.valueOf(c.getIdCampo()),c.getNombre(),String.valueOf(l.getIdLote()),p.getDescripcion(),String.valueOf(l.getEstado().getDescripcion()),String.valueOf(l.getLaboreoact())};
            dtmLpro.addRow(rowLotes);
        
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_tablaProyectosMouseClicked

    private void tablaPREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPREMouseClicked
        int indice,indl;
        Laboreo l = new Laboreo();
        List <Lotes> lotselec=  new ArrayList();
        EstadoProyecto est = new EstadoProyecto();
        Proyecto p = new Proyecto();
        Lotes lote = new Lotes();
        indice=tablaPRE.getSelectedRow();
        indl=tablaLotesP.getSelectedRow();
        
        est=control.obtenerEstado((long)2);
        l=laboreopre.get(indice);
        dtmLpro.setValueAt(l.getDescripcion(), indl, 5);
        dtmLpro.setValueAt(est.getDescripcion(), indl, 4);
        lote=lotesP.get(indl);
        lote.setEstado(est);
        lote.setLaboreoact(l.getDescripcion());
        
        if(lotselec.contains(lote)){


        }else{
                lotselec.add(lote);
                
        }
        
       
        
        
        
  
        

        
        
        
        
        
        
    }//GEN-LAST:event_tablaPREMouseClicked

    private void tablaPOSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPOSTMouseClicked
        int indice,indl;
        Laboreo l = new Laboreo();
        EstadoProyecto est = new EstadoProyecto();
        est=control.obtenerEstado((long)3);
        indice=tablaPOST.getSelectedRow();
        indl=tablaLotesP.getSelectedRow();
        l=laboreopost.get(indice);
        tablaLotesP.setValueAt(l.getDescripcion(), indl, 5);
        tablaLotesP.setValueAt(est.getDescripcion(), indl, 4);
        
        
        
        
        
    }//GEN-LAST:event_tablaPOSTMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
            
       
    
        
        
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void tablaLotesPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLotesPMouseClicked
        

        
    }//GEN-LAST:event_tablaLotesPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectosVigentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectosVigentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectosVigentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectosVigentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Finalizar;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaLotesP;
    private javax.swing.JTable tablaPOST;
    private javax.swing.JTable tablaPRE;
    private javax.swing.JTable tablaProyectos;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
